### PR TITLE
970 app state timeouts

### LINKED ISSUE #970: [all] App instance state timeouts
**Describe the bug**
App instances should have state-specific timeouts on the initial states in addition to the provided `defaultTimeouts`

### PR DESCRIPTION
**Pull request by LayneHaber**
## The Problem
Fixes #970 

NOTE: Implements defaults in the `apps` module -- these defaults should all be checked. They are (generally):
- default app timeout: 10
- state timeout for apps without action: 0
- state timeout for apps with an action: 10

## Checklist:

- [ ] I am making this PR against staging, not master
- [ ] My code follows the code style of this project.
- [ ] I have described any backwards-incompatibility implications above.
- [ ] I have highlighted which parts of the code should be reviewed most carefully.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

File: modules/cf-core/src/methods/app-instance/propose-install.ts [hunk 1]
```diff
@@ -77,6 +78,7 @@ export class ProposeInstallAppInstanceController extends NodeController {
 
     await protocolRunner.initiateProtocol(ProtocolNames.propose, {
       ...params,
+      stateTimeout: stateTimeout || Zero,
```
Comment (ArjunBhuptani) [inline modules/cf-core/src/methods/app-instance/propose-install.ts:81]: Should be stateTimeout or `undefined` (and if `undefined`, it defaults to `defaultTimeout`

File: modules/apps/src/HashLockTransferApp/registry.ts [hunk 2]
```diff
@@ -14,3 +15,6 @@ export const HashLockTransferAppRegistryInfo: AppRegistryInfo = {
   stateEncoding: HashLockTransferAppStateEncoding,
   outcomeType: OutcomeType.SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER,
 };
+
+// timeout default values
+export const HASHLOCK_TRANSFER_STATE_TIMEOUT = toBN(10);
```
Comment (ArjunBhuptani) [inline modules/apps/src/HashLockTransferApp/registry.ts:20]: This timeout refers to the timeout on initial state which should be `Zero`

File: modules/apps/src/SimpleLinkedTransferApp/registry.ts [hunk 3]
```diff
@@ -15,3 +16,5 @@ export const SimpleLinkedTransferAppRegistryInfo: AppRegistryInfo = {
   stateEncoding: SimpleLinkedTransferAppStateEncoding,
 };
 
+// timeout default values
+export const LINKED_TRANSFER_STATE_TIMEOUT = toBN(10);
```
Comment (ArjunBhuptani) [inline modules/apps/src/SimpleLinkedTransferApp/registry.ts:20]: `Zero`

File: modules/apps/src/SimpleSignedTransferApp/registry.ts [hunk 4]
```diff
@@ -14,3 +15,6 @@ export const SimpleSignedTransferAppRegistryInfo: AppRegistryInfo = {
   stateEncoding: SimpleSignedTransferAppStateEncoding,
   actionEncoding: SimpleSignedTransferAppActionEncoding,
 };
+
+// timeout default values
+export const SIGNED_TRANSFER_STATE_TIMEOUT = toBN(10);
```
Comment (ArjunBhuptani) [inline modules/apps/src/SimpleSignedTransferApp/registry.ts:20]: `Zero`

File: modules/apps/src/WithdrawApp/registry.ts [hunk 5]
```diff
@@ -14,3 +15,6 @@ export const WithdrawAppRegistryInfo: AppRegistryInfo = {
   stateEncoding: WithdrawAppStateEncoding,
   actionEncoding: WithdrawAppActionEncoding,
 };
+
+// timeout default values
+export const WITHDRAW_STATE_TIMEOUT = toBN(10);
```
Comment (ArjunBhuptani) [inline modules/apps/src/WithdrawApp/registry.ts:20]: `Zero`

File: modules/cf-core/src/models/free-balance.ts [hunk 6]
```diff
@@ -221,12 +221,12 @@ export function createFreeBalance(
...
   return new AppInstance(
     /* participants */ sortedTopLevelKeys,
-    /* defaultTimeout */ freeBalanceTimeout,
+    /* defaultTimeout */ toBN(freeBalanceTimeout).toHexString(),
     /* appInterface */ getFreeBalanceAppInterface(coinBucketAddress),
     /* appSeqNo */ HARD_CODED_ASSUMPTIONS.appSequenceNumberForFreeBalance,
     /* latestState */ serializeFreeBalanceState(initialState),
     /* latestVersionNumber */ 0,
-    /* latestTimeout */ HARD_CODED_ASSUMPTIONS.freeBalanceInitialStateTimeout,
+    /* latestTimeout */ toBN(HARD_CODED_ASSUMPTIONS.freeBalanceInitialStateTimeout).toHexString(),
```
Comment (ArjunBhuptani) [inline modules/cf-core/src/models/free-balance.ts:229]: I'm not sure if we should have state-specific timeouts in the free balance app instance.

File: modules/cf-core/src/models/state-channel.ts [hunk 7]
```diff
@@ -332,11 +334,18 @@ export class StateChannel {
     });
   }
 
-  public setState(appInstance: AppInstance, state: SolidityValueType) {
+  public setState(
+    appInstance: AppInstance,
+    state: SolidityValueType,
+    stateTimeout: BigNumber = Zero,
```
Comment (ArjunBhuptani) [inline modules/cf-core/src/models/state-channel.ts:340]: Should default to `defaultTimeout`

File: modules/node/src/appRegistry/appActions.service.ts [hunk 8]
```diff
@@ -99,9 +103,13 @@ export class AppActionsService {
...
-    await this.cfCoreService.takeAction(senderApp.identityHash, {
-      preImage: action.preImage,
-    } as SimpleLinkedTransferAppAction);
+    await this.cfCoreService.takeAction(
+      senderApp.identityHash,
+      {
+        preImage: action.preImage,
+      } as SimpleLinkedTransferAppAction,
+      LINKED_TRANSFER_STATE_TIMEOUT,
+    );
```
Comment (ArjunBhuptani) [inline modules/node/src/appRegistry/appActions.service.ts:112]: We technically dont need to specify a timeout here because this is a unilateral action that theoretically should use the `defaultTimeout` automaticallly in `progressState`

File: modules/apps/src/shared/registry.ts [hunk 9]
```diff
@@ -30,3 +31,6 @@ export type AppRegistryInfo = {
 };
 
 export type AppRegistryType = AppRegistryInfo[];
+
+// timeout default values
+export const DEFAULT_APP_TIMEOUT = toBN(10);
```
Comment (ArjunBhuptani) [inline modules/apps/src/shared/registry.ts:36]: 10 blocks is ~2 minutes which is **absolutely** not long enough. Should be at least 24h

File: modules/apps/src/DepositApp/registry.ts [hunk 10]
```diff
@@ -5,11 +5,14 @@ import {
...
     allowNodeInstall: true,
     name: DepositAppName,
     outcomeType: OutcomeType.SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER,
     stateEncoding: DepositAppStateEncoding,
   };
-  
\ No newline at end of file
+  
+// timeout default values
+export const DEPOSIT_STATE_TIMEOUT = Zero;
```
Comment (ArjunBhuptani) [inline modules/apps/src/DepositApp/registry.ts:18]: *not* `Zero`
