### PR TITLE
366 withdrawal retry

### LINKED ISSUE #366: [Client, node] Save withdrawal commitment and automatically retry
Right now, if a withdrawal fails (after generating the withdrawal commitment), the user basically has no option except to dispute their channel.

Withdrawal commitment should be saved to store and withdrawal automatically retried twice after 60s to account for cases where the packet to the hub was dropped or lost.

### PR DESCRIPTION
**Pull request by LayneHaber**
Fixes #366

### CODE REVIEW

File: modules/client/src/connext.ts [hunk 1]
```diff
@@ -496,6 +504,31 @@ export class ConnextInternal extends ConnextChannel {
...
+    // poll for withdrawal tx submitted to multisig matching tx data
+    const maxBlocks = 15; // wait 15 blocks before retrying/self-submitting
+    const startingBlock = await this.ethProvider.getBlockNumber();
+    let found;
+    interval(async (iteration, stop): Promise<void> => {
+      const currentBlock = await this.ethProvider.getBlockNumber();
+      if (currentBlock <= startingBlock) {
+        return;
+      }
+      found = await this.checkForUserWithdrawal(currentBlock, tx);
```
Comment (rhlsthrm) [inline modules/client/src/connext.ts]: Would we want to use ethers subscriptions/event listening for this instead of polling?

File: modules/client/src/controllers/WithdrawalController.ts [hunk 2]
```diff
@@ -38,7 +38,17 @@ export class WithdrawalController extends AbstractController {
           recipient,
         );
         this.log.info(`Withdraw Response: ${JSON.stringify(withdrawResponse, replaceBN, 2)}`);
-        const minTx = withdrawResponse.transaction;
+        const minTx: CFCoreTypes.MinimalTransaction = withdrawResponse.transaction;
+        // set the withdrawal tx in the store
+        // TODO: better way to set store path
+        await this.connext.store.set([
+          {
+            path: `CF_NODE:store/${this.cfCore.publicIdentifier}/latestNodeSubmittedWithdrawal`,
```
Comment (rhlsthrm) [inline modules/client/src/controllers/WithdrawalController.ts]: In my PR #362 I moved the prefix into a constant in types. We should do that here too. Hopefully my PR gets merged first so you can piggyback.

**Comment by ArjunBhuptani** [comment]
https://github.com/ConnextProject/indra/pull/396 merged, closing

**Comment by ArjunBhuptani** [comment]
Missing tests - can take a crack at it tomorrow

File: modules/client/src/connext.ts [hunk 3]
```diff
@@ -514,6 +553,60 @@ export class ConnextInternal extends ConnextChannel {
...
+  };
+
+  public watchForUserWithdrawal = async (): Promise<void> => {
+    // poll for withdrawal tx submitted to multisig matching tx data
+    const maxBlocks = 15;
+    const startingBlock = await this.ethProvider.getBlockNumber();
+
+    // TODO: poller should not be completely blocking, but safe to leave for now
+    // because the channel should be blocked
+    try {
```
Comment (rhlsthrm) [inline modules/client/src/connext.ts]: I think this try/catch needs to be inside the callback of the subscription, otherwise you are just doing a try/catch on making the subscription itself.

File: modules/client/src/connext.ts [hunk 4]
```diff
@@ -181,6 +188,36 @@ export async function connect(opts: ClientOptions): Promise<ConnextInternal> {
     ...opts, // use any provided opts by default
   });
   await client.registerSubscriptions();
+
+  // make sure there is not an active withdrawal with >= 3 retries
+  const withdrawal = await client.store.get(withdrawalKey(client.publicIdentifier));
+
+  if (withdrawal && withdrawal.retry < 3) {
```
Comment (rhlsthrm) [inline modules/client/src/connext.ts]: Let's move these magic numbers into constants.

File: modules/client/src/connext.ts [hunk 5]
```diff
@@ -1023,6 +1116,37 @@ export class ConnextInternal extends ConnextChannel {
...
+
+  public retryNodeSubmittedWithdrawal = async (): Promise<void> => {
+    const val = await this.getLatestNodeSubmittedWithdrawal();
+    if (!val) {
+      this.logger.error(`No transaction found to retry`);
+      return;
+    }
+    let { retry, tx } = val;
+    retry += 1;
+    if (retry >= 3) {
```
Comment (rhlsthrm) [inline modules/client/src/connext.ts]: Magic numbers to constants.

File: modules/client/src/connext.ts [hunk 6]
```diff
@@ -1023,6 +1116,37 @@ export class ConnextInternal extends ConnextChannel {
...
+      const msg = `Tried to have node submit withdrawal 3 times and it did not work, try submitting from wallet.`;
+      this.logger.error(msg);
+      // TODO: make this submit from wallet :)
+      // but this is weird, could take a while and may have gas issues.
+      // may not be the best way to do this
```
Comment (rhlsthrm) [inline modules/client/src/connext.ts]: Thinking the best way to do this is not to automatically do it, but inform the user and let them do it if they want to spend the gas.

Comment (ArjunBhuptani) [reply modules/client/src/connext.ts]: Not sure how best to do this^ we already log the error to console. It's kind of hard to pass back a return value here

Comment (rhlsthrm) [reply modules/client/src/connext.ts]: Well, we are throwing the error, so we can possibly put the channel in some error state that means it requires user interaction.

File: modules/client/src/connext.ts [hunk 7]
```diff
@@ -599,14 +599,14 @@ export class ConnextInternal extends ConnextChannel {
               `More than ${maxBlocks} have passed, blocks elapsed: ${blockNumber - startingBlock}`,
             );
           }
-        });
+        } catch (e) {
+          if (e.includes(`More than ${maxBlocks} have passed`)) {
```
Comment (rhlsthrm) [inline modules/client/src/connext.ts]: Still confused by this try-catch. What is actually being caught here? Why would the error include the string "More than ${maxBlocks} have passed"? Looking at the `checkForUserWithdrawal` function, I don't see it throwing an error with that message.

File: modules/client/src/connext.ts (hunk 6 above)
Comment (rhlsthrm) [reply modules/client/src/connext.ts]: Let's put this in a separate issue for now.

File: modules/client/src/connext.ts (hunk 7 above)
Comment (LayneHaber) [reply modules/client/src/connext.ts]: the promise i create throws that error if more than 15 blocks pass, then pings the hub to resubmit
